language: python

dist: bionic  # required for Python >= 3.7

branches:
  only:
    - master

cache: pip

python:
  - "3.7"
  - "3.8"

install:
  - make

script:
  - make init
  - make ci

#deploy:
#  provider: releases
#  api_key:
#    secure: *
#  file:
#    - dist/*.whl
#    - dist/*.tar.gz
#  file_glob: true
#  on:
#    repo: syspass/syspass-api-client-python
#    tags: true
#  skip_cleanup: true